In [1]:
import pandas as pd
import numpy as np
pd.__version__

'0.23.4'

In [3]:
pd? #build in documnetation

## Series

In [3]:
## Series object
data = pd.Series([0.25,0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [7]:
#data wraps calues and indices
print(data.values)
print(data.index)

[0.25 0.5  0.75 1.  ]
RangeIndex(start=0, stop=4, step=1)


In [8]:
#access data
data[1]

0.5

In [9]:
data[0:3]

0    0.25
1    0.50
2    0.75
dtype: float64

In [11]:
#string index
data2 = pd.Series([0.25,0.5,0.75,1],index=['a','b','c','d'])
data2

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [13]:
data2['c']

0.75

In [14]:
#construct series from dictionary
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
data3 = pd.Series(population_dict)

In [15]:
data3

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [16]:
data3['California']

38332521

In [18]:
data3['California':'Illinois']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [20]:
#grammer: pd.Series(data,index=index)
pd.Series([2,4,6])

0    2
1    4
2    6
dtype: int64

In [23]:
pd.Series({'a':1,'b':2,'c':3})

a    1
b    2
c    3
dtype: int64

## DataFrame

In [24]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}

In [25]:
area = pd.Series(area_dict)

In [26]:
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

In [28]:
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [31]:
states = pd.DataFrame({'population':population,'area':area})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [33]:
#properties:
print('index: ',states.index)
print('columns: ',states.columns)

index:  Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
columns:  Index(['population', 'area'], dtype='object')


In [34]:
states['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [36]:
states['population']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

In [ ]:
## Constructing DataFrames

In [39]:
pd.DataFrame(population,columns=['populations']) #from a single series

populations
California     38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135

In [42]:
data = [{'a':i,'b':2*i}
       for i in range(3)] 
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [41]:
pd.DataFrame(data) #from dictionary

a  b
0  0  0
1  1  2
2  2  4

In [44]:
pd.DataFrame(np.random.rand(3,2),  #from a numpy array
            columns=['a','b'],
            index=[1,2,3])

a         b
1  0.904125  0.974580
2  0.635014  0.482461
3  0.419937  0.399055

In [52]:
A = np.zeros(3,dtype=[('A','i8'),('B','f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [54]:
pd.DataFrame(A) #from a structured numpy array

A    B
0  0  0.0
1  0  0.0
2  0  0.0

In [ ]:
## index of DataFrame

In [60]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [61]:
ind[1] #acts like an array

3

In [62]:
ind.size

5

In [63]:
ind.shape

(5,)

In [65]:
ind.ndim

1

In [66]:
ind.dtype

dtype('int64')

In [67]:
# however, cannot be modified like ind[1]=0

In [68]:
ind2 = pd.Index([1,3,5,7,9])

In [69]:
ind & ind2 # can do set calculation

Int64Index([3, 5, 7], dtype='int64')

## indexing and selection

In [4]:
## in Series
data = pd.Series([0.25,0.5,0.75,1],index = ['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [5]:
data['b']

0.5

In [6]:
'a' in data #examine indices

True

In [7]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [11]:
data['e'] = 1.25 #assign a new index value

In [12]:
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [13]:
#slicing
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [17]:
data[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

In [18]:
#masking
data[(data>0.3)&(data<0.8)]

b    0.50
c    0.75
dtype: float64

In [19]:
#fancy indexing
data[['a','c']]

a    0.25
c    0.75
dtype: float64

In [20]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])
data

1    a
3    b
5    c
dtype: object

In [21]:
data.loc[1]

'a'

In [23]:
data.loc[1:3]

1    a
3    b
dtype: object

In [ ]:
# or iloc
#useful for integer index

In [28]:
# selection in DataFrame
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
state = pd.DataFrame({'Area':area,'Population':pop})
state

Area  Population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [31]:
state['Area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: Area, dtype: int64

In [34]:
state.Area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: Area, dtype: int64

In [36]:
# not applicable for state that has the same colum name with function

In [38]:
state['density'] = state['Population']/state['Area']
state

Area  Population     density
California  423967    38332521   90.413926
Texas       695662    26448193   38.018740
New York    141297    19651127  139.076746
Florida     170312    19552860  114.806121
Illinois    149995    12882135   85.883763

In [39]:
state.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [40]:
state.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [43]:
#transpose data
state.T

California         Texas      New York       Florida  \
Area        4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05   
Population  3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07   
density     9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02   

                Illinois  
Area        1.499950e+05  
Population  1.288214e+07  
density     8.588376e+01

In [45]:
state.iloc[:3,:2]

Area  Population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127

In [47]:
state.loc[:'Illinois', :'Population']

Area  Population
California  423967    38332521
Texas       695662    26448193
New York    141297    19651127
Florida     170312    19552860
Illinois    149995    12882135

In [54]:
state[state.density > 100]

Area  Population     density
New York  141297    19651127  139.076746
Florida   170312    19552860  114.806121

## Operating on Data

In [4]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [5]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [6]:
np.exp(df)

A            B           C            D
0   403.428793  8103.083928    7.389056   403.428793
1  1096.633158    54.598150   20.085537  1096.633158
2  1096.633158     7.389056  148.413159    54.598150

In [8]:
np.sin(df*np.pi/4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [9]:
area = pd.Series({'Alaska': 1723337, 'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521, 'Texas': 26448193,
                        'New York': 19651127}, name='population')

In [10]:
population /area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [12]:
area.index & population.index #any missing values are filled in with NaN by default:

Index(['Texas', 'California'], dtype='object')

In [14]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [15]:
# could fill NaN with values
A.add(B,fill_value=0) 

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [16]:
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns=list('AB'))

In [17]:
A

A   B
0  1  11
1  5   1

In [18]:
B = pd.DataFrame(rng.randint(0,10,(3,3)),columns=list('CBA'))

In [19]:
B

C  B  A
0  4  0  9
1  5  8  0
2  9  2  6

In [20]:
A +B #dispect order, alighed according to indices

A     B   C
0  10.0  11.0 NaN
1   5.0   9.0 NaN
2   NaN   NaN NaN

In [22]:
fill = A.stack().mean()
A.add(B, fill_value=fill) #fill with mean of all values in A

A     B     C
0  10.0  11.0   8.5
1   5.0   9.0   9.5
2  10.5   6.5  13.5

In [23]:
A = rng.randint(10, size=(3, 4))
A

array([[3, 8, 2, 4],
       [2, 6, 4, 8],
       [6, 1, 3, 8]])

In [24]:
A[0]

array([3, 8, 2, 4])

In [25]:
A - A[0] #broadcasting rule

array([[ 0,  0,  0,  0],
       [-1, -2,  2,  4],
       [ 3, -7,  1,  4]])

In [26]:
df = pd.DataFrame(A, columns=list('QRST'))
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -1 -2  2  4
2  3 -7  1  4

In [27]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0 -5  0 -6 -4
1 -4  0 -2  2
2  5  0  2  7

In [28]:
halfrow = df.iloc[0, ::2]
halfrow

Q    3
S    2
Name: 0, dtype: int32

In [29]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -1.0 NaN  2.0 NaN
2  3.0 NaN  1.0 NaN

## Handling missing data

In [1]:
import numpy as np
import pandas as pd

In [2]:
vals1 = np.array([0,None,3,4])
vals1

array([0, None, 3, 4], dtype=object)

In [4]:
vals1.sum() #error

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [5]:
vals2 = np.array([1,np.nan,3,4])
vals2

array([ 1., nan,  3.,  4.])

In [7]:
vals2.dtype

dtype('float64')

In [8]:
1+np.nan

nan

In [9]:
np.nansum(vals2) #ignore NaN

8.0

In [10]:
pd.Series([1,np.nan,2,None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [11]:
data = pd.Series([0,np.nan,'hello',None])

In [12]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [13]:
data[data.notnull()]

0        0
2    hello
dtype: object

In [14]:
data.dropna()

0        0
2    hello
dtype: object

In [15]:
df = pd.DataFrame([[1,np.nan,2],
                  [2,3,5],
                  [np.nan,4,6]])

In [16]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [17]:
df.dropna(axis=1)

2
0  2
1  5
2  6

In [18]:
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [22]:
df[0,3]=np.nan

In [23]:
df

0    1  2  (0, 2)  (0, 3)
0  1.0  NaN  2     NaN     NaN
1  2.0  3.0  5     NaN     NaN
2  NaN  4.0  6     NaN     NaN

In [24]:
df.dropna(axis=1,how="all")

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [26]:
df.dropna(axis=1,thresh=2)

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [28]:
data

0        0
1      NaN
2    hello
3     None
dtype: object

In [29]:
data.fillna(0)

0        0
1        0
2    hello
3        0
dtype: object

In [30]:
data.fillna(method='ffill')

0        0
1        0
2    hello
3    hello
dtype: object

In [31]:
data.fillna(method='bfill')

0        0
1    hello
2    hello
3     None
dtype: object

In [34]:
df.fillna(method='ffill',axis=1)

0    1    2  (0, 2)  (0, 3)
0  1.0  1.0  2.0     2.0     2.0
1  2.0  3.0  5.0     5.0     5.0
2  NaN  4.0  6.0     6.0     6.0

## Hierarchical Indexing

In [1]:
import pandas as pd
import numpy as np

In [2]:
index = [('Cal',2000),('Cal',2010),('New York',2000),('New York',2010),('Texas',2000),('Texas',2010)]
index = pd.MultiIndex.from_tuples(index)
populations = [1,2,3,4,5,6]
pop = pd.Series(populations,index=index)

In [3]:
pop

Cal       2000    1
          2010    2
New York  2000    3
          2010    4
Texas     2000    5
          2010    6
dtype: int64

In [4]:
pop[:,2010]

Cal         2
New York    4
Texas       6
dtype: int64

In [8]:
# MultiIndex as extra dimension
pop_def = pop.unstack()

In [9]:
pop_def

2000  2010
Cal          1     2
New York     3     4
Texas        5     6

In [10]:
pop_def.stack()

Cal       2000    1
          2010    2
New York  2000    3
          2010    4
Texas     2000    5
          2010    6
dtype: int64

In [16]:
pop_df = pd.DataFrame({'total':pop,'under18':[1,2,3,4,5,6]})
f_u18 = pop_df['under18']/pop_def['total']

In [17]:
f_u18

Cal       2000    1.0
          2010    1.0
New York  2000    1.0
          2010    1.0
Texas     2000    1.0
          2010    1.0
dtype: float64

In [18]:
f_u18.unstack()

2000  2010
Cal        1.0   1.0
New York   1.0   1.0
Texas      1.0   1.0

In [19]:
df = pd.DataFrame(np.random.rand(4,2),
                 index = [['a','b','a','b'],[1,1,2,2]],
                 columns = ['data1','data2'])

In [20]:
df

data1     data2
a 1  0.592767  0.065434
b 1  0.921112  0.043397
a 2  0.497120  0.358671
b 2  0.170745  0.605720

In [23]:
#build multiindex
pd.MultiIndex.from_arrays([['a','b','a','b'],[1,1,2,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 1, 0, 1], [0, 0, 1, 1]])

In [24]:
pd.MultiIndex.from_tuples(index) #tuple we create named index

MultiIndex(levels=[['Cal', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [26]:
pd.MultiIndex.from_product([['a','b'],[1,2]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [29]:
pd.MultiIndex(levels=[['a','b'],[1,2]],
             labels = [[0,0,1,1],[0,1,0,1]])

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])

In [30]:
#name the levels
pop

Cal       2000    1
          2010    2
New York  2000    3
          2010    4
Texas     2000    5
          2010    6
dtype: int64

In [32]:
pop.index.names=['state','year']

In [33]:
pop

state     year
Cal       2000    1
          2010    2
New York  2000    3
          2010    4
Texas     2000    5
          2010    6
dtype: int64

In [37]:
#MultiIndex for columns
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])
columns = pd.MultiIndex.from_product([['Bob','Guido','Sue'],['HR','Temp']],
                                    names=['subject','type'])
data = np.round(np.random.rand(4,6),1)

In [38]:
data[:,:2]

array([[0.8, 0.7],
       [0.2, 0.4],
       [0.6, 0.9],
       [0.5, 0.7]])

In [39]:
data[:,:2] *=10

In [40]:
data

array([[8. , 7. , 0.1, 0.9, 0.5, 0.1],
       [2. , 4. , 0.3, 0.3, 0.9, 0.7],
       [6. , 9. , 0.1, 0.7, 0.9, 0.5],
       [5. , 7. , 0.3, 0.8, 0.4, 0.5]])

In [41]:
data +=37

In [42]:
data

array([[45. , 44. , 37.1, 37.9, 37.5, 37.1],
       [39. , 41. , 37.3, 37.3, 37.9, 37.7],
       [43. , 46. , 37.1, 37.7, 37.9, 37.5],
       [42. , 44. , 37.3, 37.8, 37.4, 37.5]])

In [43]:
health_data = pd.DataFrame(data,index=index,columns=columns)

In [44]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      45.0  44.0  37.1  37.9  37.5  37.1
     2      39.0  41.0  37.3  37.3  37.9  37.7
2014 1      43.0  46.0  37.1  37.7  37.9  37.5
     2      42.0  44.0  37.3  37.8  37.4  37.5

In [45]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      37.1  37.9
     2      37.3  37.3
2014 1      37.1  37.7
     2      37.3  37.8

In [46]:
pop

state     year
Cal       2000    1
          2010    2
New York  2000    3
          2010    4
Texas     2000    5
          2010    6
dtype: int64

In [47]:
pop['Cal',2000]

1

In [48]:
pop['Cal']

year
2000    1
2010    2
dtype: int64

In [49]:
pop.loc['Cal':'New York']

state     year
Cal       2000    1
          2010    2
New York  2000    3
          2010    4
dtype: int64

In [50]:
pop[:,2000]

state
Cal         1
New York    3
Texas       5
dtype: int64

In [51]:
pop[pop>3]

state     year
New York  2010    4
Texas     2000    5
          2010    6
dtype: int64

In [53]:
pop[['Cal','Texas']]

state  year
Cal    2000    1
       2010    2
Texas  2000    5
       2010    6
dtype: int64

In [54]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      45.0  44.0  37.1  37.9  37.5  37.1
     2      39.0  41.0  37.3  37.3  37.9  37.7
2014 1      43.0  46.0  37.1  37.7  37.9  37.5
     2      42.0  44.0  37.3  37.8  37.4  37.5

In [57]:
health_data['Guido','HR']

year  visit
2013  1        37.1
      2        37.3
2014  1        37.1
      2        37.3
Name: (Guido, HR), dtype: float64

In [60]:
health_data.loc[:,('Bob','HR')]

year  visit
2013  1        45.0
      2        39.0
2014  1        43.0
      2        42.0
Name: (Bob, HR), dtype: float64

In [65]:
#sort
index = pd.MultiIndex.from_product([['a','b','c'],[1,2]])
data= pd.Series(np.random.rand(6),index=index)
data.index.names=['char','int']

In [66]:
data

char  int
a     1      0.330537
      2      0.761181
b     1      0.381373
      2      0.368949
c     1      0.948616
      2      0.796208
dtype: float64

In [74]:
data['a',1]

0.33053745287595215

In [75]:
data = data.sort_index()

In [76]:
data['a':'b']

char  int
a     1      0.330537
      2      0.761181
b     1      0.381373
      2      0.368949
dtype: float64

In [77]:
#stacking and unstacking
pop.unstack(level=0)

state  Cal  New York  Texas
year                       
2000     1         3      5
2010     2         4      6

In [78]:
pop.unstack(level=1)

year      2000  2010
state               
Cal          1     2
New York     3     4
Texas        5     6

In [79]:
pop.unstack().stack()

state     year
Cal       2000    1
          2010    2
New York  2000    3
          2010    4
Texas     2000    5
          2010    6
dtype: int64

In [86]:
pop_flat=pop.reset_index(name='population')

In [87]:
pop_flat.set_index(['state','year'])

population
state    year            
Cal      2000           1
         2010           2
New York 2000           3
         2010           4
Texas    2000           5
         2010           6

In [88]:
data_mean = health_data.mean(level='year')
data_mean

subject   Bob       Guido           Sue      
type       HR  Temp    HR   Temp     HR  Temp
year                                         
2013     42.0  42.5  37.2  37.60  37.70  37.4
2014     42.5  45.0  37.2  37.75  37.65  37.5

In [89]:
data_mean.mean(axis=1,level='type')

type         HR       Temp
year                      
2013  38.966667  39.166667
2014  39.116667  40.083333

## Combing dataset

In [1]:
#1.Concat and Append

In [2]:
import numpy as np
import pandas as pd

In [4]:
#function qulickly make a Data Frame
def make_df(cols,ind):
    data = {c:[str(c)+str(i) for i in ind]
           for c in cols}
    return pd.DataFrame(data,ind)
make_df('ABC',range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [5]:
#concatenate numpy arrays
x= [1,2,3]
y=[4,5,6]
z=[7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x=[[1,2],
  [3,4]]
np.concatenate([x,x],axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [8]:
#Pandas simple concatenate
#Series
ser1 = pd.Series(['A','B','C'],index=[1,2,3])
ser2 = pd.Series(['D','E','F'],index=[4,5,6])
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [11]:
#Data Frame
df1 = make_df('AB',[1,2])
df2 = make_df('CD',[3,4])
pd.concat([df1,df2])

C:\Users\woshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  after removing the cwd from sys.path.


A    B    C    D
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   C3   D3
4  NaN  NaN   C4   D4

In [14]:
df3 = make_df('AB',[0,1])
df4 = make_df('CD',[0,1])
pd.concat([df3,df4],axis=1)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1

In [15]:
x = make_df('AB',[1,2,3])
y = make_df('CD',[2,3,4])
print(x)
print(y)

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
    C   D
2  C2  D2
3  C3  D3
4  C4  D4


In [16]:
pd.concat([x,y])

C:\Users\woshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A    B    C    D
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3
4  NaN  NaN   C4   D4

In [20]:
pd.concat([x,y],verify_integrity=True)

C:\Users\woshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


ValueError: Indexes have overlapping values: Int64Index([2, 3], dtype='int64')

In [21]:
pd.concat([x,y],ignore_index=True)

C:\Users\woshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A    B    C    D
0   A1   B1  NaN  NaN
1   A2   B2  NaN  NaN
2   A3   B3  NaN  NaN
3  NaN  NaN   C2   D2
4  NaN  NaN   C3   D3
5  NaN  NaN   C4   D4

In [22]:
pd.concat([x,y],keys=['x','y']) #MultiIndex

C:\Users\woshi\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A    B    C    D
x 1   A1   B1  NaN  NaN
  2   A2   B2  NaN  NaN
  3   A3   B3  NaN  NaN
y 2  NaN  NaN   C2   D2
  3  NaN  NaN   C3   D3
  4  NaN  NaN   C4   D4

In [23]:
#concatenation with joins
df5 = make_df('ABC',[1,2])
df6 = make_df('BCD',[3,4])
pd.concat([df5,df6],join='inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [25]:
pd.concat([df5,df6],join_axes=[df5.columns])

A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

In [26]:
df1.append(df2)

C:\Users\woshi\Anaconda3\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)


A    B    C    D
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   C3   D3
4  NaN  NaN   C4   D4

## Combining Datasets: merge and join

In [1]:
import pandas as pd
import numpy as np

In [3]:
df1 = pd.DataFrame({'employee':['Bob','Jake','Lisa','Sue'],
                   'group':['Accounting','Engineering','Engineering','HR']})
df2 = pd.DataFrame({'employee':['Lisa','Bob','Jake','Sue'],
                   'hire_date':[2004,2008,2012,2014]})
print(df1)
print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [6]:
df3 = pd.merge(df1,df2)
df3

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [7]:
#many to one
df4 = pd.DataFrame({'group':['Accounting','Engineering','HR'],
                   'superisor':['Carly','Cuido','Steve']})
print(df4)
df5 = pd.DataFrame({'group':['Accounting','Accounting','Engineering','Engineering','HR','HR'],
                   'skills':['math','spreadsheets','coding','linux','spreadsheets','organization']})
print(df5)

         group superisor
0   Accounting     Carly
1  Engineering     Cuido
2           HR     Steve
         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization


In [8]:
pd.merge(df4,df5)

group superisor        skills
0   Accounting     Carly          math
1   Accounting     Carly  spreadsheets
2  Engineering     Cuido        coding
3  Engineering     Cuido         linux
4           HR     Steve  spreadsheets
5           HR     Steve  organization

In [9]:
pd.merge(df1,df2,on="employee")

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [10]:
df3 = pd.DataFrame({'name':['Bob','Jake','Lisa','Sue'],
                   'skills':[70000,80000,120000,90000]})
df3

name  skills
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000

In [11]:
pd.merge(df1,df3,left_on='employee',right_on='name').drop('name',axis=1)

employee        group  skills
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

In [12]:
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')
print(df1a)
print(df2a)

                group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
          hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014


In [13]:
pd.merge(df1a,df2a,left_index=True,right_index=True)

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [14]:
pd.merge(df1a,df3,left_index=True,right_on='name')

group  name  skills
0   Accounting   Bob   70000
1  Engineering  Jake   80000
2  Engineering  Lisa  120000
3           HR   Sue   90000

In [16]:
df1a.join(df2a)

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014

In [25]:
#sepecify set Arithmetic
df6 = pd.DataFrame({'name':['Peter','Paul','Mang'],
                   'food':['fish','bears','bead']},
                  columns=['name','food'])
df7 = pd.DataFrame({'name':['Paul','Joseph'],
                   'drink':['Wine','Bear']},
                  columns=['name','drink'])
print(df6)
print(df7)

    name   food
0  Peter   fish
1   Paul  bears
2   Mang   bead
     name drink
0    Paul  Wine
1  Joseph  Bear


In [26]:
pd.merge(df6,df7)
pd.merge(df6,df7,how="inner")

name   food drink
0  Paul  bears  Wine

In [27]:
pd.merge(df6,df7,how="outer")

name   food drink
0   Peter   fish   NaN
1    Paul  bears  Wine
2    Mang   bead   NaN
3  Joseph    NaN  Bear

In [28]:
pd.merge(df6,df7,how="left")

name   food drink
0  Peter   fish   NaN
1   Paul  bears  Wine
2   Mang   bead   NaN

In [29]:
df8 = pd.DataFrame({'name':['Bob','Jake','Lisa','Sue'],
                   'rank':[1,2,3,4]})
df9 = pd.DataFrame({'name':['Bob','Jake','Lisa','Sue'],
                   'rank':[3,1,4,2]})
print(df8)
print(df9)

   name  rank
0   Bob     1
1  Jake     2
2  Lisa     3
3   Sue     4
   name  rank
0   Bob     3
1  Jake     1
2  Lisa     4
3   Sue     2


In [30]:
pd.merge(df8,df9,on="name")

name  rank_x  rank_y
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

In [33]:
pd.merge(df8,df9,on='name',suffixes=['_L','_R'])

name  rank_L  rank_R
0   Bob       1       3
1  Jake       2       1
2  Lisa       3       4
3   Sue       4       2

## Aggregation and Grouping

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [3]:
planets = sns.load_dataset('planets')

In [5]:
planets.shape

(1035, 6)

In [7]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [11]:
decade = 10*(planets['year']//10)

In [14]:
decade = decade.astype(str)+'s'
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [17]:
decade.name='decade'
#how many discoveried planets in each decade
planets.groupby(['method',decade])['number'].sum().unstack().fillna(0)

decade                         1980ss  1990ss  2000ss  2010ss
method                                                       
Astrometry                        0.0     0.0     0.0     2.0
Eclipse Timing Variations         0.0     0.0     5.0    10.0
Imaging                           0.0     0.0    29.0    21.0
Microlensing                      0.0     0.0    12.0    15.0
Orbital Brightness Modulation     0.0     0.0     0.0     5.0
Pulsar Timing                     0.0     9.0     1.0     1.0
Pulsation Timing Variations       0.0     0.0     1.0     0.0
Radial Velocity                   1.0    52.0   475.0   424.0
Transit                           0.0     0.0    64.0   712.0
Transit Timing Variations         0.0     0.0     0.0     9.0

In [21]:
#Series
rng=np.random.RandomState(42)
ser = pd.Series(rng.rand(5))
ser

0    0.374540
1    0.950714
2    0.731994
3    0.598658
4    0.156019
dtype: float64

In [22]:
ser.sum()

2.811925491708157

In [23]:
ser.mean()

0.5623850983416314

In [25]:
#DataFrame
df = pd.DataFrame({'A':rng.rand(5),'B':rng.rand(5)})
df

A         B
0  0.183405  0.611853
1  0.304242  0.139494
2  0.524756  0.292145
3  0.431945  0.366362
4  0.291229  0.456070

In [26]:
df.mean()

A    0.347115
B    0.373185
dtype: float64

In [27]:
df.mean(axis='columns')

0    0.397629
1    0.221868
2    0.408451
3    0.399153
4    0.373650
dtype: float64

In [28]:
#example
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

In [29]:
#groupby
df = pd.DataFrame({'key':['A','B','C','A','B','C'],
                  'data':range(6)},columns=['key','data'])
df

key  data
0   A     0
1   B     1
2   C     2
3   A     3
4   B     4
5   C     5

In [30]:
df.groupby('key').sum()

data
key      
A       3
B       5
C       7

In [31]:
#column indexing
planets.groupby('method')

In [32]:
planets.groupby('method')['orbital_period']

In [35]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

In [39]:
for (method, group) in planets.groupby('method'):
    print(method, group.shape)

Astrometry (2, 6)
Eclipse Timing Variations (9, 6)
Imaging (38, 6)
Microlensing (23, 6)
Orbital Brightness Modulation (3, 6)
Pulsar Timing (5, 6)
Pulsation Timing Variations (1, 6)
Radial Velocity (553, 6)
Transit (397, 6)
Transit Timing Variations (4, 6)


In [42]:
planets.groupby('method')['year'].describe() #describe of year in each method group

count         mean       std     min      25%  \
method                                                                         
Astrometry                       2.0  2011.500000  2.121320  2010.0  2010.75   
Eclipse Timing Variations        9.0  2010.000000  1.414214  2008.0  2009.00   
Imaging                         38.0  2009.131579  2.781901  2004.0  2008.00   
Microlensing                    23.0  2009.782609  2.859697  2004.0  2008.00   
Orbital Brightness Modulation    3.0  2011.666667  1.154701  2011.0  2011.00   
Pulsar Timing                    5.0  1998.400000  8.384510  1992.0  1992.00   
Pulsation Timing Variations      1.0  2007.000000       NaN  2007.0  2007.00   
Radial Velocity                553.0  2007.518987  4.249052  1989.0  2005.00   
Transit                        397.0  2011.236776  2.077867  2002.0  2010.00   
Transit Timing Variations        4.0  2012.500000  1.290994  2011.0  2011.75   

                                  50%      75%     max  
method                                                  
Astrometry                     2011.5  2012.25  2013.0  
Eclipse Timing Variations      2010.0  2011.00  2012.0  
Imaging                        2009.0  2011.00  2013.0  
Microlensing                   2010.0  2012.00  2013.0  
Orbital Brightness Modulation  2011.0  2012.00  2013.0  
Pulsar Timing                  1994.0  2003.00  2011.0  
Pulsation Timing Variations    2007.0  2007.00  2007.0  
Radial Velocity                2009.0  2011.00  2014.0  
Transit                        2012.0  2013.00  2014.0  
Transit Timing Variations      2012.5  2013.25  2014.0

In [54]:
df = pd.DataFrame({'key':['A','B','C','A','B','C'],
                  'data1':range(6),
                  'data2':[1,1,1,2,2,2]},
                 columns=['key','data1','data2'])

In [55]:
#aggregation
df.groupby('key').aggregate(['min',np.median,max])

data1            data2           
      min median max   min median max
key                                  
A       0    1.5   3     1    1.5   2
B       1    2.5   4     1    1.5   2
C       2    3.5   5     1    1.5   2

In [56]:
df.groupby('key').aggregate({'data1':'min','data2':'max'})

data1  data2
key              
A        0      2
B        1      2
C        2      2

In [58]:
#filtering
def filter_func(x):
    return x['data2'.std()>4]

In [63]:
df.groupby('key').std()

data1     data2
key                   
A    2.12132  0.707107
B    2.12132  0.707107
C    2.12132  0.707107

In [66]:
#Specify group key
L = [0,1,0,1,2,0]
df.groupby(L).sum()

data1  data2
0      7      4
1      4      3
2      4      2

In [67]:
df.groupby(df['key']).sum()

data1  data2
key              
A        3      3
B        5      3
C        7      3

In [68]:
df2 = df.set_index('key')

In [69]:
mapping = {'A':'vowel','B':'consonant','C':'consonant'}

In [71]:
df2.groupby([str.lower,mapping]).mean()

data1  data2
a vowel        1.5    1.5
b consonant    2.5    1.5
c consonant    3.5    1.5

## Pivot tables

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns

In [2]:
titanic = sns.load_dataset('titanic')

In [3]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [5]:
titanic.groupby(['sex'])[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

In [7]:
titanic.groupby(['sex','class'])[['survived']].aggregate('mean').unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [10]:
#same as multi-dimensional groupby
titanic.pivot_table('survived',index='sex',columns='class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [17]:
fare = pd.qcut(titanic['fare'],2)
age = pd.cut(titanic['age'],[0,18,80])

In [18]:
titanic.pivot_table('survived',['sex',age],[fare,'class'])

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First   
sex    age                                                               
female (0, 18]               NaN  1.000000  0.714286          0.909091   
       (18, 80]              NaN  0.880000  0.444444          0.972973   
male   (0, 18]               NaN  0.000000  0.260870          0.800000   
       (18, 80]              0.0  0.098039  0.125000          0.391304   

fare                                 
class              Second     Third  
sex    age                           
female (0, 18]   1.000000  0.318182  
       (18, 80]  0.914286  0.391304  
male   (0, 18]   0.818182  0.178571  
       (18, 80]  0.030303  0.192308

In [23]:
#aggfunc control aggregation type
titanic.pivot_table(index='sex',columns='class',aggfunc={'survived':sum,'fare': 'mean'})

fare                       survived             
class        First     Second      Third    First Second Third
sex                                                           
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

In [27]:
titanic.pivot_table('survived',index='sex',columns='class',margins=True)

class      First    Second     Third       All
sex                                           
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

## Vectorized String Operations

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = ['peter','Paul',None,'MARY','gUIDO']

In [3]:
names = pd.Series(data)
names

0    peter
1     Paul
2     None
3     MARY
4    gUIDO
dtype: object

In [4]:
names.str.capitalize()

0    Peter
1     Paul
2     None
3     Mary
4    Guido
dtype: object

In [5]:
monte = pd.Series(['Graham Chapman','John Cleese','Terry Gillam','Eric Idle','Terry Jones','Micharl Palin'])
monte.str.len()

0    14
1    11
2    12
3     9
4    11
5    13
dtype: int64

In [6]:
monte.str.lower()

0    graham chapman
1       john cleese
2      terry gillam
3         eric idle
4       terry jones
5     micharl palin
dtype: object

In [8]:
monte.str.startswith('T')

0    False
1    False
2     True
3    False
4     True
5    False
dtype: bool

In [10]:
monte.str.split()

0    [Graham, Chapman]
1       [John, Cleese]
2      [Terry, Gillam]
3         [Eric, Idle]
4       [Terry, Jones]
5     [Micharl, Palin]
dtype: object

In [11]:
#extract first name
monte.str.extract('([A-Za-z]+)',expand=False)

0     Graham
1       John
2      Terry
3       Eric
4      Terry
5    Micharl
dtype: object

In [12]:
#^start of $ end of
monte.str.findall(r'^[^AEIOU]*[^aeiou]$') #start and end with a consonant

0    [Graham Chapman]
1                  []
2      [Terry Gillam]
3                  []
4       [Terry Jones]
5     [Micharl Palin]
dtype: object

In [13]:
monte.str[0:3] #first three letters

0    Gra
1    Joh
2    Ter
3    Eri
4    Ter
5    Mic
dtype: object

In [14]:
#get last name
monte.str.split().str.get(-1)

0    Chapman
1     Cleese
2     Gillam
3       Idle
4      Jones
5      Palin
dtype: object

In [15]:
full_monte = pd.DataFrame({'name':monte,'info':['B|C|D','B|D','A|C','B|D','B|C','B|C|D']})

In [16]:
full_monte

name   info
0  Graham Chapman  B|C|D
1     John Cleese    B|D
2    Terry Gillam    A|C
3       Eric Idle    B|D
4     Terry Jones    B|C
5   Micharl Palin  B|C|D

In [18]:
full_monte['info'].str.get_dummies('|')

A  B  C  D
0  0  1  1  1
1  0  1  0  1
2  1  0  1  0
3  0  1  0  1
4  0  1  1  0
5  0  1  1  1

## Working with Time Series

In [ ]:
#Pandas best in Python to work with datatime in data science

In [19]:
import pandas as pd

In [23]:
date = pd.to_datetime('4th of July, 2015')
date

Timestamp('2015-07-04 00:00:00')

In [24]:
data.strftime('%A') #day of the week

'Saturday'

In [25]:
data + pd.to_timedelta(np.array(12),'D')

Timestamp('2015-07-16 00:00:00')

In [28]:
index = pd.DatetimeIndex(['2014-07-04','2014-08-04','2015-07-04','2015-08-04'])

In [29]:
data = pd.Series([0,1,2,3],index=index)

In [30]:
data

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [31]:
#index and slicing
data['2014-07-04':'2015-07-04']

2014-07-04    0
2014-08-04    1
2015-07-04    2
dtype: int64

In [32]:
data['2015']

2015-07-04    2
2015-08-04    3
dtype: int64

In [35]:
dates = pd.to_datetime(['4th of July, 2015', '2015-jul-6','07-07-2015','20150708'])

In [36]:
dates

DatetimeIndex(['2015-07-04', '2015-07-06', '2015-07-07', '2015-07-08'], dtype='datetime64[ns]', freq=None)

In [37]:
dates.to_period('D')

PeriodIndex(['2015-07-04', '2015-07-06', '2015-07-07', '2015-07-08'], dtype='period[D]', freq='D')

In [38]:
dates-dates[0]

TimedeltaIndex(['0 days', '2 days', '3 days', '4 days'], dtype='timedelta64[ns]', freq=None)

In [40]:
pd.date_range('2015-07-03','2015-07-10')

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [41]:
pd.date_range('2015-07-03',periods=8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [42]:
pd.date_range('2015-07-03',periods=8,freq="H")

DatetimeIndex(['2015-07-03 00:00:00', '2015-07-03 01:00:00',
               '2015-07-03 02:00:00', '2015-07-03 03:00:00',
               '2015-07-03 04:00:00', '2015-07-03 05:00:00',
               '2015-07-03 06:00:00', '2015-07-03 07:00:00'],
              dtype='datetime64[ns]', freq='H')

In [43]:
pd.period_range('2015-07',periods=8,freq='M')

PeriodIndex(['2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12',
             '2016-01', '2016-02'],
            dtype='period[M]', freq='M')

In [44]:
pd.timedelta_range(0,periods=10,freq="H")

TimedeltaIndex(['00:00:00', '01:00:00', '02:00:00', '03:00:00', '04:00:00',
                '05:00:00', '06:00:00', '07:00:00', '08:00:00', '09:00:00'],
               dtype='timedelta64[ns]', freq='H')

In [ ]:
#frequencies adnd offsets

In [1]:
import pandas as pd

In [1]:
from pandas_datareader import data

In [3]:
#goog = data.DataReader('GooG',start='2004',end='2016',data_source='google')
#data not available any more! (see note for reference or the book)

## Last topic in pandas: hi-performance pandas

In [ ]:
# advantage: S-speed operations without costly memory

In [1]:
#vectorized operations in numpy
import numpy as np

In [3]:
rng = np.random.RandomState(42)

In [4]:
x = rng.rand(1000000)

In [5]:
y = rng.rand(1000000)

In [6]:
%timeit x+y

4.89 ms ± 810 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
import numexpr

In [10]:
%timeit mask_numpexpr=numexpr.evaluate('(x>0.5)&(y<0.5)')   #more efficient

4.27 ms ± 126 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
#Pandas.eval()
import pandas as pd

In [13]:
nrows,ncols = 100000,100

In [14]:
rng = np.random.RandomState(42)

In [15]:
df1,df2,df3,df4 = (pd.DataFrame(rng.rand(nrows,ncols)    )          for i in range(4) )

In [18]:
%timeit dfs = df1+df2+df3+df4

135 ms ± 4.56 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
%timeit dfs2=pd.eval('df1+df2+df3+df4') #faster

63.7 ms ± 4.14 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [22]:
df1,df2,df3,df4,df5= (pd.DataFrame(rng.randint(0,100,(100,3))    )          for i in range(5) )

In [25]:
result = pd.eval('-df1*df2/(df3+df4)-df5')
result.head()

0           1           2
0  -62.666667  -55.945455 -214.352941
1  -32.178082  -54.217391 -187.750000
2 -162.166667  -35.914729  -48.121951
3  -62.639344 -130.682927 -104.534884
4 -134.338028  -65.000000   -8.081081

In [26]:
result2 = pd.eval('df1<df2<=df3!=df4')
result2.head()

0      1      2
0  False  False  False
1   True  False  False
2  False  False  False
3  False  False  False
4  False  False   True

In [27]:
result3 = pd.eval('(df1<0.5)&(df2<0.5)|(df3<df4)')
result3.head()

0      1      2
0  False  False  False
1   True   True  False
2   True  False  False
3   True   True   True
4  False  False   True

In [29]:
result4 = pd.eval('df1.T[0]+df3.iloc[1]')
result4.head()

0    105
1     71
2    116
dtype: int32

In [30]:
#columnwise operaions: eval () in DataFrame
df = pd.DataFrame(rng.rand(1000,3),columns=['A','B','C'])
df.head()

A         B         C
0  0.783604  0.745539  0.956174
1  0.001479  0.312814  0.994176
2  0.485142  0.294374  0.400381
3  0.213437  0.574808  0.952865
4  0.506592  0.345608  0.123266

In [32]:
result1 = pd.eval('(df.A+df.B)/(df.C-1)')
result2 = df.eval('(A+B)/(C-1)')

In [34]:
np.allclose(result1,result2)

True

In [35]:
df.eval('D=(A+B)/C',inplace=True)

In [38]:
df.head()

A         B         C         D
0  0.783604  0.745539  0.956174  1.599232
1  0.001479  0.312814  0.994176  0.316135
2  0.485142  0.294374  0.400381  1.946935
3  0.213437  0.574808  0.952865  0.827236
4  0.506592  0.345608  0.123266  6.913517

In [58]:
column_mean = df.mean()
column_mean.head()

A    0.496937
B    0.507783
C    0.510887
D    5.184935
dtype: float64

In [60]:
result=df.eval('A + @column_mean') #involves an avaible name
result.head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
dtype: float64

In [51]:
Cmean = df['C'].mean()
Cmean

0.5108869180023007

In [52]:
result = df.query('A < @Cmean & B < @Cmean')

In [53]:
result.head()

A         B         C         D
1   0.001479  0.312814  0.994176  0.316135
2   0.485142  0.294374  0.400381  1.946935
4   0.506592  0.345608  0.123266  6.913517
11  0.227712  0.282785  0.502264  1.016394
14  0.149080  0.024347  0.422472  0.410505